### PR TITLE
perf(repeat): stateless strategies

### PR DESCRIPTION
**Pull request by jdanyow**
@EisenbergEffect / @martingust this is the change to make strategies stateless to enable reusing strategy instances. This will reduce memory usage in two-dimensional array/repeat scenarios and help enable some of the other perf changes we're planning. Integration tests are passing, I just need to get the unit tests passing.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Cool. Keep the improvements coming! Let me know when you are ready to merge.

**Comment by jdanyow** [comment]
ok this is all set- all tests passing, tried it in a couple projects

**Comment by EisenbergEffect** [comment]
Make it so! :stars:

**Comment by martingust** [comment]
@jdanyow  Awesome, looking real good, great improvements!

**Pull request merged**
