### PR TITLE
fix(repeat): bug when "if.bind", "repeat.for" and animations are used in a certain way

### PR DESCRIPTION
**Pull request by Alexey1**
closes https://github.com/aurelia/animator-velocity/issues/21 and
https://github.com/aurelia/templating-resources/issues/298

### CODE REVIEW

**Comment by Alexey1** [comment]
Please, note, I didn't do according test change because existing tests container for ```repeat``` is set up in such way that it tests ```repeat``` from a jspm package instead of one from the source code. Reported in https://github.com/aurelia/templating-resources/issues/300 .

**Comment by zewa666** [comment]
Thanks for the PR, I'll try to get as soon as possible to verify that the fix doesn't break the CSS Animator.

**Comment by zewa666** [comment]
ok so I've checked the css animator with your fix and it works as well 👍 
since @jdanyow already review the change in one of the mentioned issues I think we can safely merge this one @EisenbergEffect

**Comment by zewa666** [comment]
@Alexey1 thanks again for the help

**Comment by Alexey1** [comment]
no problem

**Pull request merged**
