### PR TITLE
test(repeat): use the component tester

### PR DESCRIPTION
**Pull request by martingust**
@EisenbergEffect This requires `testing` to be released with [this](https://github.com/aurelia/testing/pull/14).

@jdanyow There are two tests failing I couldn't get to pass, [this](https://github.com/aurelia/templating-resources/blob/master/test/hide.spec.js#L36) for `hide` and [this](https://github.com/aurelia/templating-resources/blob/master/test/show.spec.js#L36) for `show`. Looks like same issue, both giving me `Expecting undefined to be true`. Any ideas?

### CODE REVIEW

**Comment by jdanyow** [comment]
There's a few calls to `withResources()` with no args.  I think this method on the component tester only accepts an array.

After replacing those with `withResources([])` there's an error [here](https://github.com/aurelia/testing/blob/master/src/component-tester.js#L58) because host.firstElementChild is null.

**Comment by martingust** [comment]
@jdanyow I've created a PR in testing that removes the need for providing resources, that will need to be released in order for these tests to pass.

**Comment by EisenbergEffect** [comment]
@martingust I can merge that if you can revert the change to the eslint.json file

**Comment by jdanyow** [comment]
@martingust I think all the tests are broken- repeat included.  Hit karma's debug button and check the console

**Comment by EisenbergEffect** [comment]
I only had two failing tests. Make sure all your deps are up to date.

**Comment by martingust** [comment]
Same here, also two failing in latest CI build https://circleci.com/gh/aurelia/templating-resources/14

**Pull request merged**
