### PR TITLE
Repeat strategy pattern

### PR DESCRIPTION
**Pull request by martingust**
@EisenbergEffect This is work in progress to (possible) get @jdanyow started doing his work and for you to review. The implementation should be pretty ready, but needs more testing, might want to break the strategy classes out to different files. Unit tests need more work and probably not green atm.

### CODE REVIEW

**Comment by martingust** [comment]
Maybe the strategy locator should use a Map lookup table [here](https://github.com/aurelia/templating-resources/blob/strategy-pattern/src/array-collection-strategy.js#L12-L18) for user to overwrite and add additional strategies.

**Comment by EisenbergEffect** [comment]
Yes, we should definitely do something like that. I'm wondering if the container could handle it directly somehow, maybe with a custom resolver. I need to think about it. Do the strategies have state? I'm also wondering if some of this should be pushed into binding. @jdanyow We had some good  feedback from jods about making collection observation easier, in general. Maybe these strategies are the start of the work for that. I haven't reviewed yet. Need to hope on a plane. Will take a look later today.

**Comment by martingust** [comment]
@EisenbergEffect Yes, they have state. I synchronised some more work. Strategies split into different files and fixed up the unit tests. Though not able to get `createModelForUnitTest` to work after getting latest from a few other repos. Probably need to update more repos.

**Comment by EisenbergEffect** [comment]
@martingust How are we on this. Ready to merge?

**Comment by martingust** [comment]
@EisenbergEffect Not yet. I'm going to do some more work/testing in a few hours on this and hopefully wrap it up. Does the implementation look alright to you?

**Comment by EisenbergEffect** [comment]
@martingust OOPS! I just merged it.

**Comment by EisenbergEffect** [comment]
I also updated it to work with the latest master of templating...

**Comment by stoffeastrom** [comment]
haha :) trigger happy today ;P

**Comment by EisenbergEffect** [comment]
If you make additional changes, can you submit another PR with the new stuff? Sorry, I was a bit hasty...

**Comment by martingust** [comment]
haha oops! Yeah, I'll create new PR for additional work.

**Pull request merged**
