### PR TITLE
perf(all): synchronous resources registration

### PR DESCRIPTION
**Pull request by bigopon**
@EisenbergEffect this is to go together with https://github.com/aurelia/framework/pull/858 

I have delayed the load of view factory & compiling process in the framework configuration until all resources have been loaded. This changes isn't necessary to avoid breaking existing code, it's just a mean to use the new api.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@bigopon Is this an old PR?

**Comment by bigopon** [comment]
Yes, but it will still works fine after new framework PR, as it still use same API `globalResources` @EisenbergEffect

**Comment by EisenbergEffect** [comment]
Gotcha!

**Comment by bigopon** [comment]
@EisenbergEffect This is in good state to merge after aurelia/framework#885

**Comment by EisenbergEffect** [comment]
Will final review this and the other PR this weekend. Thanks!

**Comment by EisenbergEffect** [comment]
@bigopon Can you remove the `d.ts` file from this PR? After that, I'm ready to merge.

**Comment by bigopon** [comment]
I think we should also move `@inject` to `static inject` for DOM.Element injection. These framework code folks cannot control and will have hard to if PLATFORM code is not called at appropriate time @EisenbergEffect

**Comment by EisenbergEffect** [comment]
@bigopon I saw you do that in one place already...I think it was for the SlotAttribute. It makes sense. If you want to add that to this PR, that's fine with me.

**Comment by EisenbergEffect** [comment]
@bigopon It's in! What's next? Are there any more PRs besides the templating-router one that we need to get in to complete the feature?

**Comment by bigopon** [comment]
That's it, `templating-router` is the last one for first batch @EisenbergEffect

**Pull request merged**
