### PR TITLE
chore(html-sanitizer): add an explicit security warning to the constructor of htmlsanitizer

### PR DESCRIPTION
**Pull request by fkleuver**
with regards to https://discourse.aurelia.io/t/vulnerability-disclosure-contact/2390

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Note: Do not merge until docs updated with instructions.

**Comment by EisenbergEffect** [comment]
Actually, I think you've linked the right place. It didn't look right at first but I see that's where the current note is. So, I'm going to go ahead and merge this. We can add more to the docs at that location.

**Comment by fkleuver** [comment]
@EisenbergEffect Let's just wait until I get a response from the person who reported it?

**Comment by EisenbergEffect** [comment]
I added a bit more to the documentation. Not published yet, but pushed to GH.

**Comment by EisenbergEffect** [comment]
@fkleuver Can we merge this now and release?

**Comment by fkleuver** [comment]
@EisenbergEffect yep

**Pull request merged**
