### PR TITLE
fix updates during leave animation

### PR DESCRIPTION
**Pull request by ohjames**
This is an in process PR for fixing #167 

It currently just includes a test that demonstrates the issue.

### CODE REVIEW

**Comment by ohjames** [comment]
@martingust have a fix here. It works almost perfectly but if we can coalesce the splices (see https://github.com/ohjames/templating-resources/blob/0549456ee2c5645e78cc1297ed2dfa30ab68abe4/src/array-repeat-strategy.js#L121) then it will be much better/simpler and ready for commit/review.

The test passes anyway with the fix as it is.

**Comment by ohjames** [comment]
Okay I have the normalising in place now in e557cfb should be ready to merge. With this fix things run a lot better on my website, no more exceptions thrown from aurelia :) It'll need a small change to `aurelia-binding`, to export `mergeSplice`.

On the down side.. they still aren't quite perfect. Although I think the only remaining bug is duplicate elements appear in the view (over the top of non-duplicated elements that should be in their place).

**Comment by martingust** [comment]
@ohjames Looks solid, unit tests passing and I ran a few succesful tests scenarios in skeleton. The remaining bug is that something you think you can get in a fix with this PR or create a new issue for that?

**Comment by ohjames** [comment]
@martingust Cool, I'll open a new github issue for the remaining bug. Would be great to get this merged, it improves things *a lot*.

**Comment by EisenbergEffect** [comment]
@ohjames I can merge and do a release on Monday assuming this is an incremental fix and doesn't require your next PR. I can release that when it's available too...I just want to make sure I don't need to wait in order to sync things without breaking people. Does that make sense?

**Comment by ohjames** [comment]
@EisenbergEffect It would be great to release this fix ASAP I think given how severe the issue is and how easy it is to manifest, it depends on the PR against aurelia/binding only.

**Comment by EisenbergEffect** [comment]
@ohjames  Just to be clear, in order to release this, I must first release this: https://github.com/aurelia/binding/pull/265 Correct?

**Comment by ohjames** [comment]
@EisenbergEffect affirmative

**Pull request merged**
