### PR TITLE
fix(repeat): update binding context after animations have finished

### LINKED ISSUE #94: repeat updates executionContext on items too early if au-animate
If there is `au-animate` on the repeated element, when splicing the Array the execution context gets updated too early here: https://github.com/aurelia/templating-resources/blob/master/src/repeat.js#L283-L292. There are still all children in the viewSlot as their removal is delayed by the Animator here: https://github.com/aurelia/templating/blob/master/src/view-slot.js#L137-L140

Therefore the execution context is wrong after the elements got finally removed (e.g. $index is wrong)

The repeater should wait there if the Element is animatable. I tried to implement it but was not sure how to best get all the leave promises of the animatable children here: https://github.com/aurelia/templating-resources/blob/master/src/repeat.js#L283

I'd appreciate any hints how to get these promises best and would happily help with  sending in a PR or with testing or whatnot.

### PR DESCRIPTION
**Pull request by martingust**
Fixes #94

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@martingust I made some changes throughout related to binding context names. Can you rebase or re-apply your changes to the latest? Sorry about this ;(

**Comment by EisenbergEffect** [comment]
@martingust I need you to rebase this on master please. There have been some breaking changes to the internals of templating that affected this.

**Comment by martingust** [comment]
@EisenbergEffect No problem, will do. After pulling the latest I'm getting error running the tests after upgrading `karma-jspm` to v2.0.1. Do you know off hand what the issue is? If not I will continue tonight or tomorrow to get this in, sorry for the delay.

WARN [web-server]: 404: /base/aurelia-loader.js
Chrome 40.0.2214 (Mac OS X 10.10.4) ERROR: 'Potentially unhandled rejection [8] Error: XHR error (404 Not Found) loading http://localhost:9876/base/aurelia-loader.js
    at error (http://localhost:9876/base/jspm_packages/system.src.js?662c5eaab59718da347a899ec3dc1239f458b2c2:1028:16)
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost:9876/base/jspm_packages/system.src.js?662c5eaab59718da347a899ec3dc1239f458b2c2:1036:13)'

**Comment by martingust** [comment]
@EisenbergEffect I reimplemented the fix and tests to the latest. However I'm still not able to get the tests to run for some reason  (so we might don't want to merge this just yet). They run fine on the v.0.14.0 commit, however from the next commit (https://github.com/aurelia/templating-resources/commit/44693a2816722d29dcf7da24dbc6d6e86d54a5fe) and on  I'm getting the error above. Are you able to run the tests? Please let me know if you have any ideas.

**Comment by martingust** [comment]
Oh ok, `aurelia-loader` needed to be added. The tests run but some are failing. Let me look into that and commit again.

**Comment by martingust** [comment]
@EisenbergEffect Fix should be in, `aurelia-loader` installed, `karma-jspm` updated, and tests fixed up, I hope I got it all right. 

There are still a couple of tests for `if` that is currently not passing, that I wasn't able to look more into this time, but I think it has something to do with the latest caching improvements.

**Pull request merged**
