### PR TITLE
chore(all): convert to TS

### LINKED ISSUE #300: repeat.spec.js tests repeat object from jspm package instead of one from the project source
**I'm submitting a bug report**

* **Library Version:**
1.4.0

**Please tell us about your environment:**
* **Operating System:**
Windows 8

* **Node Version:**
6.9.2

* **NPM Version:**
4.3.0

* **JSPM OR Webpack AND Version**
Aurelia CLI 0.30.1

* **Browser:**
Chrome 60

* **Language:**
TypeScript 2.4.2

**Current behavior:**
repeat.spec.js tests file
jspm_packages/npm/aurelia-templating-resources@1.0.0-rc.1.0.2/repeat.js 
instead of file
src/repeat.js

STR:
1. Setup as described in Readme.md
2. Add "debugger;" line in one of the tests like so:
```
it('should do nothing if no items provided', () => {
      let didThrow = false;
      repeat.items = undefined;

      try {
        debugger;
        repeat.bind();
      } catch (e) {
        didThrow = true;
      }

      expect(didThrow).toBe(false);
    });
```
2. Run command ```karma start```

3. Open dev tools in karma browser

4. Refresh page if needed, wait until "debugger" line starts debug mode

5. Step into repeat.bind(); method

6. Notice the repeat.js file is from jspm package instead of the project source:
image

**Expected/desired behavior:**

Repeat object is loaded from src/repeat.js file.

**Additional observations**:
I guess the reason for this is that repeat object from Repeat class imported like this
```import {Repeat} from '../src/repeat';```
is never created. Instead one retrieved like this 
```component = StageComponent.withResources().inView('<div repeat.for="item of items"></div>').boundTo({ items: [] });```
```...```
```repeat = component.viewModel;```
is used and it comes from jspm package.

### LINKED ISSUE #321: cleanup: replace oneWay with toView, add toView + fromView binding behavior
We have some binding behaviors that set the binding mode. Now that we have toView and fromView binding modes we should add the corresponding binding behaviors:

https://github.com/aurelia/templating-resources/blob/0cef07a8cac8e99146d8e1c4b734491bb3dc4724/src/binding-mode-behaviors.js

Also need to standardize the internals on `toView` now that it has landed. We still need to support `oneWay` but the internals should use `toView` where possible.

related to https://github.com/aurelia/binding/issues/629 and https://github.com/aurelia/templating-binding/issues/118

### LINKED ISSUE #332: tests for repeat is not testing the source code in src/ folder.
**I'm submitting a bug report**

* **Library Version:**
1.5.4 (this should affect all versions since the beginning)

* **Operating System:**
OSX 10.13

* **Node Version:**
8.5.0

* **NPM Version:**
5.5.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Browser:**
NA

* **Language:**
NA

**Current behavior:**
I was investigating the ci test failure on latest v1.5.4 build.
It's a failure test about `unbind()` call for `repeat`. It turns out it is NOT testing the latest source code in src/ folder. It was testing against the aurelia-templating-resource package (very very old version) installed by jspm.

It was all started with this line in test.
```javascript
component = StageComponent.withResources().inView('<div repeat.for="item of items"></div>').boundTo({ items: [] });
```

`withResources()` has no input, it just uses what aurelia loaded, which is all custom attributes coming from the aurelia-templating-resource package installed by jspm.

I tried to use `withResources('src/repeat')`, but aurelia rejected my attempt by saying 
```
Attempted to register an Attribute when one with the same name already exists. Name: repeat.
```
which is reasonable.

I tried to created a `test/repeat-test.js` to extend Repeat (just like `test/if-test.js` did) to hook up local test to `repeatt.for` instead of `repeat.for`, but could not pass the line
```javascript
this.sourceExpression = getItemsSourceExpression(this.instruction, 'repeat.for');
```
in original `src/repeat.js`.
ES6 doesn't allow me to skip super(...) in RepeatTest constructor, which runs the above line I need to 
skip and override with `getItemsSourceExpression(this.instruction, 'repeatt.for');`

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
Need to find a way for all tests around `repeat` to against local source code, not against package installed by jspm.

### PR DESCRIPTION
**Pull request by bigopon**
Beside conversion, also add ability to configure `Compose` behavior to not inherit binding context by default via entry `configure` function:

```ts
export function configure(config: any, { useLegacyBehavior = true } = {}); {
  Compose.useLegacyBehavior = useLegacyBehavior;
}
```

It's based on @jdanyow 's comment here https://github.com/aurelia/templating-resources/issues/222#issuecomment-294858777

Though I'm not sure when `Compose` is configured to not inherit binding context, it should throw or just silently inherit when composed with view only instruction.

Besides that, adjust build, so now distribution will be a single file with sourcemap enabled. Something like this
image

@EisenbergEffect @jdanyow @jods4 @fkleuver 

@fkleuver What should i adjust circle CI of this to?

@huochunpeng 
resolves #332 
resolves #300
resolves #321

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Wow! @bigopon You are a beast! This is awesome. How should we proceed. I'm not sure if I have a ton of time to review every line. I trust your work though :) Is there anything in particular we should look at, any concerns, details left to polish up?

**Comment by bigopon** [comment]
@EisenbergEffect The plan is like this:

in `templating-router` and `templating-resources`, accept 2nd paramter for `configure` function to toggle legacy behavior for `Compose` and `RouterView`.

in `framework`, add method `enableLegacyBehavior(enabled: boolean)` to `FrameworkConfiguration` to pass that to those two modules.

Write some doc for this.

Details to look at:

There are two way to toggle `Compose` behavior:
- at start up time: like explained above
- at any time: `Compose.useLegacyBehavior = true/false` (default is `true` for compat). I'm not sure about naming.

**Comment by bigopon** [comment]
About the conversion, it's not that much of a big deal I think. Most typings are still kept any for safety reasons. Mostly it's the build/tests/development flow that are cleaner now

**Comment by EisenbergEffect** [comment]
@bigopon Instead of using the generic terms "legacy behavior" can we instead make the property name more explicit in what it's doing? For example `allowParentScopeTraversal = true` or something like that. Not sure exactly what the name would be.

**Comment by bigopon** [comment]
@EisenbergEffect that sounds good to me. Will need to adjust router view accordingly. What about view only composition, do we want to auto traverse parent, or throw?

**Comment by EisenbergEffect** [comment]
For view-only composition, remind me what happens with the binding context. Does it get nothing if it doesn't traverse? That doesn't seem right. Is there a reason we would treat this scenario differently?

**Comment by bigopon** [comment]
It points to the `Compose` element with its `overrideContext` https://github.com/aurelia/templating-resources/blob/6aa889b2f8aa92ca6a9b8acb3a0ba4bdca7372d7/src/compose.ts#L227L228

Which I think it will automatically inherit owning view of `compose` by default. So only need some tests, no need to change anything here

**Comment by EisenbergEffect** [comment]
If it inherits the owning view, that sounds ideal.

**Comment by bigopon** [comment]
@EisenbergEffect here are the two skipped tests
* https://github.com/aurelia/templating-resources/pull/374/files/6aa889b2f8aa92ca6a9b8acb3a0ba4bdca7372d7..5347777153b3ee4b8b90a63fe570d72910827f8f#diff-342077e7f5694040ec714108a9a1234aR134 
* https://github.com/aurelia/templating-resources/pull/374/files/6aa889b2f8aa92ca6a9b8acb3a0ba4bdca7372d7..5347777153b3ee4b8b90a63fe570d72910827f8f#diff-342077e7f5694040ec714108a9a1234aR150

I just realized when adding some integration tests for compose, that `<router-view/>` and `<compose/>` do composition differently. `<router-view/>` controls the behavior instruction, while `<compose/>` does not.

For this, I think I'll have to add something in templating.

**Comment by EisenbergEffect** [comment]
@bigopon I'd rather just delete the code than comment it out usually. Was there a strong argument for doing it this way?

**Comment by bigopon** [comment]
@EisenbergEffect Removed

**Comment by bigopon** [comment]
@EisenbergEffect one of throttle tests is failing, its' probably non-deterministic timing related, we can fix that later.

**Pull request merged**
