### PR TITLE
Added hide binding and tests for show.

### PR DESCRIPTION
**Pull request by Einarsson**
I would like to have a hide binding as already discussed here in #177 
While at it I also added tests for the show binding

### CODE REVIEW

**Comment by jdanyow** [comment]
@Einarsson awesome :+1: 

Can you confirm you've signed the [CLA](http://goo.gl/forms/dI8QDDSyKR)

cc @EisenbergEffect

**Comment by Einarsson** [comment]
@jdanyow Yes, I've signed it before. :)

**Comment by martingust** [comment]
Very nice Emil!

**Comment by EisenbergEffect** [comment]
CLA confirmed. Definitely happy to add the hide behavior, especially since you wrote tests for both show and hide. Awesome!

**Comment by Einarsson** [comment]
Great! Just happy I can be of use at times. :)

**Comment by jdanyow** [comment]
:shipit: :rocket:

**Pull request merged**
