### PR TITLE
added an au-src attribute

### PR DESCRIPTION
**Pull request by capaj**
this is not ready to be merged, I would love to add some basic test at least. Unfortunately I can't seem to run them on my machine, will try some linux machine soon. 
Another matter is to make this behavior global as are all the other behaviors here in this folder. Where is that configured?

### CODE REVIEW

**Comment by Aaike** [comment]
i also experienced this when doing `src="${image}"`
i have been avoiding this problem by using `src.bind="image"`

**Comment by capaj** [comment]
@Aaike I did not know that could work. Then it is probably not needed. It would be nice to mention it in the docs somewhere, so that people are not falling into the same issue.

**Comment by jdanyow** [comment]
@EisenbergEffect can you re-open this one?  We can handle this like the textarea interpolation:

https://github.com/aurelia/templating-binding/blob/master/src/binding-language.js#L205

**Comment by jdanyow** [comment]
whoops- thought this was an issue not a pull- my bad

**Pull request closed without merging**
